name: KAS Deploy Process

# Trigger the workflow on push to the main branch
on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Deploy to the server
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.8 # Use a stable version instead of `master`
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Navigate to the project directory
            cd /bmod/kas-be

            # Pull the latest changes
            git pull origin main

            # Activate the virtual environment
            source venv/bin/activate

            # Install updated dependencies
            pip install --upgrade pip
            pip install -r requirement.txt

            # Apply migrations
            python manage.py migrate

            # Restart the Gunicorn service
            sudo systemctl restart kas.gunicorn

            # Deactivate the virtual environment
            deactivate
